BLOCKv.podspec, BlockV/Classes/BVError.swift, BlockV/Classes/Network/Params/TokenRegisterParams.swift, Example/BlockV/Controllers/Inventory/InventoryCollectionViewController.swift, Example/BlockV/Info.plist
- fix crash on iOS 10 due to missing NSPhotoLibraryUsageDescription
- cancel activate image downloads on deinit
- add authentication limit error
- bump podspec to 0.9.4
=> Minor improvements

BLOCKv.podspec, BlockV/Classes/BLOCKv+Request.swift, BlockV/Classes/BLOCKv.swift, BlockV/Classes/Network/Stack/OAuth2Handler.swift, Example/BlockV.xcodeproj/project.pbxproj, Example/BlockV/Base.lproj/Main.storyboard, Example/Podfile.lock
The 3rd party lib JWTDecode is used simply to determine if the JWT has expired.
=> Fixes an issue with refreshing the access token

BLOCKv.podspec, README.md
=> update podspec to 0.9.7

BlockV/Classes/BLOCKv+Request.swift, BlockV/Classes/BVError.swift, BlockV/Classes/Network/Models/User/PublicUserModel.swift, BlockV/Classes/Network/Models/User/UserToken.swift, BlockV/Classes/Network/Params/TokenRegisterParams.swift, BlockV/Classes/Network/Stack/API.swift, BlockV/Classes/Network/Stack/Client.swift, BlockV/Classes/Network/Stack/OAuth2Handler.swift, Example/BlockV/Controllers/VerifyTableViewController.swift
This commit adds the ability to create, update, and delete user tokens.
=> Add user token endpoints

BLOCKv.podspec, Example/BlockV/Info.plist, README.md
update example app version
update readme
=> update pod version to 1.0.0

BlockV/Classes/BLOCKv.swift, BlockV/Classes/Network/Stack/API.swift, BlockV/Classes/Network/Stack/Client.swift, BlockV/Classes/Network/Stack/Endpoint.swift, BlockV/Classes/Requests/BLOCKv+UserRequests.swift
- Remove access to client request methods
=> Add internal API to delete current user (testing only)

BlockV/Core/BVError.swift, BlockV/Core/Network/Stack/Client.swift, BlockV/Core/Network/Stack/DataRequest+JSONDecode.swift, Example/BlockV_Unit_Tests/BVError_Tests.swift
remove redundant error language from BVError cases
=> add equatable conformance

BlockV/Core/Network/Models/Package/FaceModel.swift
change displayURL from type URL to String
=> remove view mode enum

.gitignore, Example/BlockV.xcodeproj/project.pbxproj
- Deleted the secrets folder, added the secret file directly to .gitignore
=> fix secret file

BlockV/Face/Face Views/Image/ImageFaceView.swift
- fixes an issue with the config param key name
=> Fix: Config param key name

BlockV/Core/Web Socket/Models/WSStateUpdateEvent.swift, Example/BlockV/Controllers/Inventory/InventoryCollectionViewController.swift
- remove the dictionary wrap around JSON (this is a breaking change)
=> Feature: Core - State event JSON

Example/BlockV/Views/LiveVatomView.swift
- Only permit updates to vatom where the updated vatom's id matches the current
=> Fix: Face - ID check on state update

Example/BlockV/Views/LiveVatomView.swift
- Add initialiser to `LiveVatomView` which takes no arguments.
=> Fix: Compile issue

BlockV/Face/Extensions/UIImageView+Ext.swift, BlockV/Face/Face Views/FaceViewRoster.swift, BlockV/Face/Face Views/Progress Image/ProgressImageFaceView.swift, Example/BlockV/Views/LiveVatomView.swift
- Adds the progress image overlay face view as an embedded face view.
=> Feature: Face - Progress image overlay face view

Example/BlockV/Controllers/Inventory/InventoryCollectionViewController.swift, Example/BlockV/Views/LiveVatomView.swift
- Fixes some memory leaks by capturing closures using a weak reference.
=> Example: Fix - Signal weak capture

Example/BlockV/Controllers/Inventory/InventoryCollectionViewController.swift
- Remove fetch inventory call after state update
=> Example: Remove state update

BlockV/Face/Face Views/Utilities/VatomObserverStore.swift
lint
docs
change stop to cancel
=> Face: Fix - minor improvements to vatom observer store

BlockV/Face/Face Views/Web/Face Bridge/CoreBridge.swift, BlockV/Face/Face Views/Web/Face Bridge/CoreBridgeV1.swift, BlockV/Face/Face Views/Web/Face Bridge/CoreBridgeV2.swift
- Core bridge protocol
- Implementation for V1
- Stubs for V2
=> Feature: Add core bridge protocol

BLOCKv.podspec, Example/BlockV.xcodeproj/project.pbxproj, Example/BlockV/AppDelegate.swift, Example/BlockV/Utility/CustomProcedure.swift, Example/Podfile, Example/Podfile.lock
Re-add 3D face now that the circular dependency is resolved.
=> Fix: 3d face

BlockV/Core/BLOCKv.swift, BlockV/Core/Requests/BLOCKv+AuthRequests.swift
Manage data pool in the BLOCKv lifecycle.
=> Core: Feature - Data pool creation

Example/BlockV/Actions.storyboard, Example/BlockV/Controllers/Actions/ActionListTableViewController.swift, Example/BlockV/Controllers/Actions/OutboundActionViewController.swift, Example/BlockV/Extensions/UIAlertController+Etx.swift, Example/BlockV/Extensions/UIColor+Ext.swift
Add functionality to sample app:
- Perform action (limited to Share, Clone, Redeem)
- Delete vatom
=> Sample: Feature - Action sheet

BlockV/Core/Data Pool/Helpers/Vatom+PreemptiveActions.swift
Add preemptive actions to core.
=> Core: Feature - Preemptive actions

BlockV/Core/Data Pool/Core+Overlays.swift, BlockV/Core/Data Pool/DataPool.swift, BlockV/Core/Data Pool/Regions/InventoryRegion.swift, BlockV/Core/Network/Stack/Client.swift
Convery `requestData` and `requestJSON` to use the concurrent dispatch queue.
=> Core: Fix - Data pool issues

BlockV/Core/Data Pool/DataPool.swift, BlockV/Core/Data Pool/Regions/BLOCKvRegion.swift, BlockV/Core/Data Pool/Regions/InventoryRegion.swift, BlockV/Core/Data Pool/Regions/VatomIDRegion.swift
This PR:
- Adds `VatomIDRegion`
- Moves vatom parsing up to `BLOCKvRegion`
- Clean up
=> Core: Fix - Data pool improvements

BlockV/Core/Data Pool/Core+Overlays.swift, BlockV/Core/Data Pool/Helpers/Vatom+PreemptiveActions.swift, BlockV/Core/Network/Stack/Client.swift, BlockV/Core/Requests/BLOCKv+ActivityRequests.swift, BlockV/Core/Requests/BLOCKv+AuthRequests.swift, BlockV/Core/Requests/BLOCKv+UserRequests.swift, BlockV/Core/Requests/BLOCKv+VatomRequest.swift, BlockV/Face/Face Views/Utilities/VatomObserver.swift, BlockV/Face/Face Views/Utilities/VatomObserverStore.swift, BlockV/Face/Face Views/Web/Face Bridge/CoreBridgeV1.swift, BlockV/Face/Face Views/Web/Face Bridge/CoreBridgeV2.swift
- Update public completion handlers to complete with a `Result` type.
=> Core: Feature - Result type

BlockV/Face/Face Views/Web/Face Bridge/CoreBridge.swift, BlockV/Face/Face Views/Web/Face Bridge/CoreBridgeV1.swift, BlockV/Face/Face Views/Web/Face Bridge/CoreBridgeV2.swift, BlockV/Face/Face Views/Web/WebFaceView.swift, BlockV/Face/Face Views/Web/WebScriptMessageHandler.swift
- Add support for Bridge Protocol 2.1
- Bug fixes
=> Core: Feature - Native bridge 2.1

BlockV/Face/Extensions/UIImageView+Ext.swift, BlockV/Face/Face Views/Image Layered/ImageLayeredFaceView.swift, BlockV/Face/Face Views/Image Policy/ImagePolicyFaceView.swift, BlockV/Face/Face Views/Image Progress/ImageProgressFaceView.swift, BlockV/Face/Face Views/Image/ImageFaceView.swift, BlockV/Face/Vatom View/DefaultErrorView.swift
This PR add a target size to the images allowing Nuke to scale down the image placed into the view. This reduces the memory footprint especially for huge images.
=> Face: Fix - Image scaling

BlockV/Core/Data Pool/Helpers/Vatom+Containment.swift
Fix child template variation id filter
=> Core: Fix - Vatom containment

BlockV/Core/Network/Models/AppUpdateModel.swift, BlockV/Core/Network/Stack/API+TypedResponses.swift, BlockV/Core/Requests/BLOCKv+AuthRequests.swift
Expose endpoint to get app update and support information.
=> Core: Feature - App version support

BlockV/Face/Face Views/Web/WebFaceView.swift
Update caching policy from `loadIgnoringLocalAndRemoteCacheData` to `useProtocolCachePolicy`
=> Fix: Web face caching

BlockV/Face/Vatom View/VatomView.swift
Ensure load completion executes on the main queue
=> Fix: Face - VVLC load queue

BlockV/Core/Helpers/OAuth/AuthorizationServer.swift
- Add padding to the url query params to remove border line.
=> Core: Fix - OAuth border

BlockV/Core/Network/Params/TokenRegisterParams.swift
Add nonPushNotification property to control email/sms system messages.
=> Core: Fix - nonPushNotification

BlockV/Face/Vatom View/FaceMessageDelegate.swift, BlockV/Face/Vatom View/VatomView.swift
- Fixes crash were the selected face view is nil
- Refactors VVLC into smaller functions
=> Core: Fix - Vatom view vvlc

BlockV/Core/BLOCKv.swift
Fixes an issue where the web socket would not connect on session launch.
=> Core: Fix - Web socket connect

BlockV/Core/Data Pool/DataObjectAnimator.swift, BlockV/Core/Data Pool/Regions/Region.swift
Add a source field to the update notification to inform the listener of the source of the update.
=> Core: Fix - Region update source

BlockV/Face/Extensions/Nuke+AnimatedImage.swift, BlockV/Face/Face Views/FaceView.swift, BlockV/Face/Face Views/Image/ImageFaceView.swift, BlockV/Face/Vatom View/DefaultErrorView.swift
Make `FaceView` a subclass of `BoundedView` to provide a method informing subclasses of when the bounds are set. This is important for image scaling.
=> Face: Fix - Image target size

BlockV/Core/Helpers/DelayOptions.swift, BlockV/Core/Web Socket/WebSocketManager.swift
Auto reconnect the socket after an unintentional disconnect
=> Core: Feature - Auto reconnect web socket

BlockV/Face/Face Views/Image Policy/ImagePolicyFaceView.swift
Add two root property value lookups:
- `cloning_score`
- `num_direct_clones`
=> Fix: Image policy face

BlockV/Core/Data Pool/Regions/GeoPosRegion.swift, BlockV/Core/Data Pool/Regions/Region+Notifications.swift, BlockV/Core/Web Socket/Models/WSMapEvent.swift, BlockV/Core/Web Socket/WebSocketManager.swift, Example/BLOCKv Unit Tests/Models/Web Socket/MockWebSocket.swift, Example/BLOCKv Unit Tests/Models/Web Socket/WebSocketEvent_Tests.swift, Example/BlockV.xcodeproj/project.pbxproj
This PR adds the `'map'` web socket event to the WebSocketManager and GeoPosRegion.
=> Core: Feature - Web socket map update

BlockV/Core/Network/Models/Activity/MessageModel.swift, Example/BLOCKv Unit Tests/Models/ActivityModel_Tests.swift, Example/BlockV.xcodeproj/project.pbxproj
Adds public member-wise initialiser to `MessageModel`
=> Core: Fix - Message model init

BlockV/Core/Data Pool/Helpers/Vatom+PreemptiveActions.swift, BlockV/Core/Data Pool/Regions/BLOCKvRegion.swift, BlockV/Core/Data Pool/Regions/InventoryRegion.swift, BlockV/Core/Data Pool/Regions/Region+Notifications.swift, BlockV/Core/Data Pool/Regions/Region.swift
Create symmetric events: will and did
=> Core: Fix - Region events

BlockV/Core/Web Socket/Models/WSInventoryEvent.swift, BlockV/Core/Web Socket/Models/WSStateUpdateEvent.swift
Add action name to `WSInventoryEvent` and `WSStateUpdateEvent`
=> Core: Fix - Action name

BlockV/Core/Network/Models/Package/UnpackedModel.swift, BlockV/Core/Network/Stack/API+TypedResponses.swift, BlockV/Core/Network/Stack/API.swift, BlockV/Core/Requests/BLOCKv+VatomRequest.swift
Add ability to fetch a single vatom in a more convenient manner.
Add fetch vatom payload to API layer.
=> Core: Fix - Single vatom

BlockV/Core/BLOCKv.swift, BlockV/Core/BVEnvironment.swift, BlockV/Core/Data Pool/DataPool.swift, BlockV/Core/Data Pool/Regions/BLOCKvRegion.swift, BlockV/Core/Data Pool/Regions/GeoPosRegion.swift, BlockV/Core/Data Pool/Regions/InventoryRegion.swift, BlockV/Core/Data Pool/Regions/Region.swift, BlockV/Core/Data Pool/Regions/VatomChildrenRegion.swift, BlockV/Core/Helpers/OAuth2Handler.swift, BlockV/Core/Web Socket/WebSocketManager.swift, BlockV/Face/Face Views/Web/Face Bridge/CoreBridgeV1.swift, BlockV/Face/Face Views/Web/WebFaceView.swift, BlockV/Face/Face.swift, BlockV/Face/Vatom View/VatomView.swift
Convert print statements to os_log
=> Core: Feature - Logging

BlockV/Core/BVError.swift, BlockV/Core/Helpers/OAuth/AuthorizationServer.swift, BlockV/Core/Requests/BLOCKv+AuthRequests.swift, BlockV/Face/Resources/DataDownloader.swift, Public.swift
Complete with OAuth flow query param, e.g. register.
=> Core: Feature - OAuth flow

BlockV/Core/BVError.swift, BlockV/Core/Network/Stack/Client.swift
- Add missing error mappings
- Construct platform error if data is available
=> Core: Fix - Error mapping

BlockV/Core/Data Pool/Regions/Region.swift
=> Core: Fix - Save ref cycle

BlockV/Core/Web Socket/WebSocketManager.swift
- Explicitly disconnect socket when entering background
- Reconnect on entering foreground
=> Core: Fix - Socket reconnect

Example/BLOCKv Unit Tests/Miscellaneous/KeyPath_Tests.swift, Example/BLOCKv Unit Tests/Mocks/MockModel.swift, Example/BLOCKv Unit Tests/Models/FaceModel_Tests.swift
- Fix key path tests
- Add sprite face decoding tests
=> Core: Fix - Tests

BlockV/Core/Helpers/KeyPath.swift
- Remove escaped double quotes
- Pass array of elements to key path query
=> Core: Fix - Key path nested strings

BlockV/Core/Helpers/OAuth2Handler.swift
Ensure token expiration is detected.
=> Core: Fix - OAuth handler

BlockV/Core/Data Pool/Regions/GeoPosRegion.swift
=> Core: Fix - Geo pos region

BlockV/Core/Network/Stack/API+TypedResponses.swift, BlockV/Core/Network/Stack/API.swift, BlockV/Core/Requests/BLOCKv+VatomRequest.swift
Adds the endpoints and convenience function to allow merchants to request redemption on a particular vatom.
=> Core: Feature - Request redemption

BlockV/Core/BVError.swift
=> Core: Fix - Update errors

BlockV/Core/Helpers/OAuth2Handler.swift
Ensure requests are retired only once.
Delay retires for network-level timeouts by 1 second.
=> Core: Fix - Timeout retry

BlockV/Core/Network/Models/AssetProviderModel.swift
Sort query params before appending to URL.
=> Core: Fix - Encoding

BlockV/Face/Face Views/FaceView.swift
Expose FaceError enum to allow viewers to use it.
=> Face: Fix - Face error access

BlockV/Core/BVError.swift
Error 17 indicates the user has attempted an action with a location that has 'significantly' changed from their previous location.
=> Core: Fix - Add error 17

BlockV/Face/Face Views/CommonFaceConfig.swift, BlockV/Face/Face Views/FaceView.swift
1. Add types common to all faces using trigger rules, e.g. `OnEvent`
2. Add `FacePresenter` protocol. This protocol should be conformed to by types that are presenting a face (not limited to UIView).
3. Add extension to `FacePresenter` with convenience methods for finding trigger rules.
=> Face: Feature - Trigger rules

BlockV/Core/Models/Package/Vatom/VatomUpdateModel.swift
=> Core: Fix - Model property access

BlockV/Core/BLOCKv.swift, BlockV/Core/Requests/BLOCKv+VatomRequest.swift
- Add `onActionStart` and `onActionComplete` closures which allow the viewer to intercept all actions.
=> Core: Feature - Action pipeline

BlockV/Face/Face Views/Image Layered/ImageLayeredFaceView.swift, BlockV/Face/Face Views/Image Policy/ImagePolicyFaceView.swift, BlockV/Face/Face Views/Web/WebFaceView.swift
- `listCachedChildren` is now a throwing function.
=> Face: Fix: Throwing `listCachedChildren`

BlockV/Face/Face Views/Web/Face Bridge/CoreBridgeV2.swift
Support token verification status.
=> Core: Feature - Bridge protocol 2.1

BlockV/Core/BVError.swift, BlockV/Core/Models/Top Level/ErrorModel.swift, BlockV/Core/Network/Stack/Client.swift, BlockV/Core/Network/Stack/DataRequest+JSONDecode.swift
Add request id to platform errors. This allows the viewer to use the request id for debugging/support requests.
=> Core: Fix - BVError request id

BlockV/Face/Face Views/Image Progress/ImageProgressFaceView.swift
Update Image Progress Face View to use constraints. This avoids artefacts when animating the frame of VatomView.
=> Face - Fix - Image progress animation

BlockV/Face/Face Views/Image Progress/ImageProgressFaceView.swift
- Check for zero bounds before laying out.
- Capture self weakly
=> Face: Fix - Image progress layout

BlockV/Core/Models/User/UserModel.swift, BlockV/Core/Network/Stack/API+TypedResponses.swift, BlockV/Core/Requests/BLOCKv+AuthRequests.swift
- Add ability for clients to generate a guest id.
- Fix decoding issues in `UserModel`.
=> Core: Fix - Generate guest id

BlockV/Core/Data Pool/DataObject.swift, BlockV/Core/Data Pool/Regions/BLOCKvRegion.swift, BlockV/Core/Data Pool/Regions/InventoryRegion.swift, BlockV/Core/Data Pool/Regions/Region.swift, BlockV/Core/Models/Package/Vatom/VatomUpdateModel.swift, BlockV/Core/Requests/BLOCKv+VatomRequest.swift, BlockV/Face/Vatom View/VatomView.swift
- This PR fixes an issue where parent-id side effect update where not being passed through to vatom-view. This was apparent when adding/removing children from folders.
=> Core: Fix - Parent id side effects

Sources/Core/Data Pool/Regions/Region.swift
=> Fix: Premptive return

.gitignore, BLOCKv.podspec
- Bump Podspec version to 3.2.0
=> Fix: Cocoapods support

Sources/Core/Models/Activity/MessageModel.swift, Sources/Core/Models/Package/Face/FaceModel+Descriptable.swift, Sources/Core/Models/Package/Face/FaceModel.swift, Sources/Core/Models/User/UserModel.swift, Tests/BLOCKv-Unit-Tests/Mocks/MockModel.swift, Tests/BLOCKv-Unit-Tests/Models/Codable/FaceModelCodable_Tests.swift
- Safely decode json of type null.
- Add unit test to validate this.
=> Core: Fix - Nullable array

Sources/Core/Models/Package/Face/FaceModel.swift
- Remove unnecessary try
- Add member wise init to Face Model
=> Fix: Core - Model adjustments

Sources/Core/Web Socket/WebSocketManager.swift
Prevent reconnect is the user is not logged in.
=> Fix: Core - Web socket reconnect

Sources/Core/Data Pool/Regions/GeoPosRegion.swift, Sources/Core/Web Socket/WebSocketManager.swift
Expose `monitorRegion(:)` to viewer.
Move extension to MKCoordinateRegion to WebSocketManager
=> Core: Feature: Expose monitorRegion
