BLOCKvIO/ios-sdk

BlockV/Core/Network/Params/DiscoverQueryBuilder.swift, BlockV/Core/Requests/BLOCKv+VatomRequest.swift
- Depreciate discover count
- Only append `filter` array to discover payload if a filter element is present.
=> Core: fix - discover count

BlockV/Core/Network/Models/Package/VatomModel.swift
Allow for absent `unpublished` key. Default to `false` if absent.
=> Core: fix - vatom model unpublished

BlockV/Core/Helpers/Result.swift
This is a temporary addition. It is a placeholder until Swift 5 is released.
=> Core: Feature - Add Result type from Swift

BlockV/Face/Face Views/Web/WebScriptMessageHandler.swift, BlockV/Face/Vatom View/FaceMessageDelegate.swift, BlockV/Face/Vatom View/VatomView.swift, Example/BlockV/Controllers/Inventory/TappedVatomViewController.swift, Example/BlockV/Views/LiveVatomView.swift
1. Expand `VatomViewDelegate` to include two new methods:
- `vatomView(:didSelectFaceView:)`
- `vatomView(:didLoadFaceView:)`
these methods allow a vatom-view host to keep better informed about the Vatom View Lifecycle (VVLC).
2. All `VatomViewDelegate` methods now use the `Result` type in their completion closure. This is in preparation for the Swift 5 release.
=> Face: Fix - Expand VatomViewDelegate 

BLOCKv.podspec, BlockV/Core/Helpers/Result.swift, BlockV/Core/Network/Models/Package/ActionModel.swift, BlockV/Core/Network/Models/Package/FaceModel.swift, BlockV/Core/Network/Models/Package/VatomModel.swift, BlockV/Core/Network/Models/Package/VatomResourceModel.swift, BlockV/Face/Face Views/Image Progress/ImageProgressFaceView.swift, BlockV/Face/Face Views/Web/WebFaceView.swift
- Constrain Starscream to 3.0.6 since it's Swift version is still 4.2
- Fix legacy hashing
- Fix lint warnings
=> Core: Fix - Minor issues

BlockV/Face/Vatom View/DefaultErrorView.swift, BlockV/Face/Vatom View/VatomView.swift
- VatomView missing `commonSetup` path on no argument init.
- Add gif support to default error view.
=> Face: Fix: Face issues

BlockV/Core/Helpers/OAuth/AuthorizationServer.swift, BlockV/Core/Network/Models/OAuthTokenExchangeModel.swift, BlockV/Core/Network/Stack/API+TypedResponses.swift, BlockV/Core/Network/Stack/Client.swift, BlockV/Core/Requests/BLOCKv+AuthRequests.swift
This PR removes the `TemporaryOAuthTokenExchangeModel` and replaces it with `OAuthTokenExchangeModel` which aligns with the API change (made to meet the OAuth spec).
=> Core: Fix - OAuth V2

BlockV/Face/Vatom View/DefaultErrorView.swift, BlockV/Face/Vatom View/VatomView.swift
Fixes and issue where a load closure could affect the state of a vatom-view even after the vatom-view's vatom had changed..
=> Core: Fix - Vatom view reuse pool

BlockV/Face/Extensions/Nuke+AnimatedImage.swift, BlockV/Face/Face Views/Image Layered/ImageLayeredFaceView.swift, BlockV/Face/Face Views/Image Policy/ImagePolicyFaceView.swift, BlockV/Face/Face Views/Image Progress/ImageProgressFaceView.swift, BlockV/Face/Face Views/Image/ImageFaceView.swift, BlockV/Face/Vatom View/DefaultErrorView.swift
This PR:
1. Adjusts the cache key to include the target size to ensure that when Nuke reaches for it's in-memory cache, it fetches images which also meet the target size criteria. Note: Nuke's `cacheKey` property on `ImageRequest` is used as the in-memory caching key and does not affect on disk caching.
2. Creates and abstract class `BoundedView` which has a function `layoutWithKnownBounds()` that is called once the bounds of self are known. This is important when the view is constrained using auto-layout and the bounds are only known after `layoutSubviews()` has been called.
=> Face: Fix - Cache key to include target size

BlockV/Core/Data Pool/Regions/InventoryRegion.swift
Fix an issue where the `processedPageCount` did not increment correctly.
=> Core: Fix - Inventory region max page

BlockV/Core/Network/Models/User/AddressAccountModel.swift, BlockV/Core/Network/Stack/API+TypedResponses.swift, BlockV/Core/Requests/BLOCKv+UserRequests.swift, Example/BLOCKv Unit Tests/Miscellaneous/BVError_Tests.swift, Example/BLOCKv Unit Tests/Mocks/MockAddressModel.swift, Example/BLOCKv Unit Tests/Models/Codable/AddressModelCodable_Tests.swift, Example/BlockV.xcodeproj/project.pbxproj, Example/Podfile, Example/Podfile.lock
This PR will:
- Expose the api request for fetching the users blockchain accounts
=> Feature: Add current user blockchain address request

BlockV/Core/Data Pool/Regions/InventoryRegion.swift, BlockV/Core/Network/Models/Package/Action/ActionModel+Descriptor.swift, BlockV/Core/Network/Models/Package/Face/FaceModel+Descriptable.swift, BlockV/Core/Network/Models/Package/Vatom/VatomModel+Descriptor.swift, BlockV/Face/Face Views/Web/Face Bridge/CoreBridgeV2.swift, Example/.swiftlint.yml
Add `//swiftlint:disable identifier_name` to file due to a [bug](https://github.com/realm/SwiftLint/issues/1762) in Switlint preventing underscores to be used in identifier names.
=> Fix: Linter

BlockV/Face/Face Views/FaceView.swift, BlockV/Face/Face Views/Image Layered/ImageLayeredFaceView.swift, BlockV/Face/Face Views/Image Policy/ImagePolicyFaceView.swift, BlockV/Face/Face Views/Image Progress/ImageProgressFaceView.swift, BlockV/Face/Face Views/Image/ImageFaceView.swift, BlockV/Face/Face Views/Web/WebFaceView.swift, BlockV/Face/Vatom View/VatomView.swift
Update face view to use a throwing initialiser. This is useful when the face config is a prerequisite for the face's initialisation (and no sensible defaults can be used, e.g. SpriteSheet face view).
=> Face: Fix - Face view throwing initialiser

BlockV/Core/Extensions/String+Core Etx.swift, BlockV/Core/Helpers/KeyPath.swift, BlockV/Core/Web Socket/WebSocketManager.swift, BlockV/Face/Face Views/Image Policy/ImagePolicyFaceView.swift
- Consolidate key path lookup logic.
- Account for nested string key paths.
=> Core: Fix - Keypath lookup

BlockV/Face/Face Views/Image Policy/ImagePolicyFaceView.swift, BlockV/Face/Face Views/Image Progress/ImageProgressFaceView.swift
Fixes an issue where the private section is not evaluated when the face config is `null`.
=> Face: Fix - Face config

BlockV/Core/Helpers/OAuth2Handler.swift
Reverts BLOCKvIO/ios-sdk#299
This change does not properly address the issue. I am reverting for now.
=> Revert "Core: Fix - OAuth handler"

BlockV/Core/BLOCKv.swift
Update `reset` to clear region cache and shared url cache.
=> Core: Fix - SDK reset additions

BlockV/Core/Data Pool/Helpers/Vatom+PreemptiveActions.swift, BlockV/Core/Data Pool/Regions/BLOCKvRegion.swift, BlockV/Core/Data Pool/Regions/InventoryRegion.swift, BlockV/Core/Data Pool/Regions/Region.swift
1. Distribute pick and drop preemptive updates to all regions.
2. Ensure preemptive changes to 'vatom' data objects (in `BLOCKvRegion` subclasses) have their `sync_nr` set as `-1`. This indicates to the region the vatom object is out of sync with remote.
3. Ensure any preemptive change in the `InventoryRegion` resets the hash to `nil`.
=> Core: Fix - Preemptive updates

BlockV/Core/Helpers/OAuth2Handler.swift
- Only append bearer token to endpoints requiring authorisation.
=> Core: Fix: Bearer token endpoint scope

BlockV/Core/Data Pool/DataPool.swift, BlockV/Core/Data Pool/Helpers/Vatom+ChildLookup.swift, BlockV/Core/Data Pool/Regions/Region.swift, BlockV/Core/Models/Package/Vatom/VatomModel+Containment.swift
- Add `get(ids)` to `Region`.
- Update `listCachedChildren` to be a throwing function. This improves the safety of the function by informing the caller when the vatom is unowned, i.e. unsupported by the function.
=> Core: Feature - Region additions

BlockV/Core/BLOCKv.swift, BlockV/Core/Extensions/Notification+Ext.swift, BlockV/Core/Requests/BLOCKv+VatomRequest.swift
- Remove action closures on `BLOCKv`.
- Broadcast `willPerformAction` and `didPerformAction`.
A notification based approach is better suited since it allows multiple observers to respond to the action pipeline.
=> Core: Feature - Perform action notifications

BlockV/Face/Vatom View/VatomView.swift
- Call `runVVLC` synchronously within init.
- Only call `vatomChanged(:)` if the model value has changed.
=> Core: Fix - Vatom View LC
